parser:
  allow_remote: true

generator:
  convenient_errors: "off"
  features:
    enable:
      # Enables paths server generation
      - "paths/server"
      # Enables validation of server responses
      - "server/response/validation"
      # Enables stub Handler generation
      - "ogen/unimplemented"
    disable_all: true
