services:
    db:
      image: postgres:17.2-alpine3.20
      restart: unless-stopped
      ports:
        - 15432:5432
      volumes:
        - ./migrations/psql:/docker-entrypoint-initdb.d
      environment:
        POSTGRES_DB: devdb
        POSTGRES_USER: devuser
        POSTGRES_PASSWORD: devpassword
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -q -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
        interval: 20s
        start_period: 10s
        timeout: 10s
        retries: 5