openapi: '3.0.3'
info:
  title: Project Alpha core API
  version: '0.1'
servers:
  - url: api/v1


paths:
  /users:
    get:
      tags:
        - user
      summary: Получить всех пользователей
      description: Получить всех пользователей
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'schemas/responses/users.yaml#/UsersResponse'
    post:
      tags:
        - user
      summary: Создать нового пользователя
      description: Создать нового пользователя
      responses:
        '201':
          description: Создан
          content:
            application/json:
              schema:
                $ref: 'schemas/responses/user.yaml#/UserResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'schemas/base/user.yaml#/User'

      
  /users/{id}:
    get:
      tags:
        - user
      summary: Получить пользователя по ID
      description: Получить пользователя по ID
      parameters:
        - name: include
          in: query
          schema:
            type: array
            items:
              type: string
              enum:
                - groups
                - roles
                - projects
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: 'schemas/responses/user.yaml#/UserResponse'
    put:
      tags:
        - user
      summary: Обновить пользователя по ID
      description: Обновить пользователя по ID
      responses:
        '200':
          description: Обновлен
          content:
            application/json:
              schema:
                $ref: 'schemas/responses/user.yaml#/UserResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'schemas/base/user.yaml#/User'

    delete:
      tags:
        - user
      summary: Удалить пользователя по ID
      description: Удалить пользователя по ID
      responses:
        '204':
          description: Удален

  /users/{id}/roles:
    put:
      tags:
        - user
      summary: Установить роли пользователя
      description: Установить роли пользователя
      responses:
        '200':
          description: Роли обновлены
          content:
            application/json:
              schema:
                $ref: 'schemas/responses/roles.yaml#/RolesResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'schemas/responses/roles.yaml#/RolesResponse'


  /groups:
    get:
      tags:
        - group
      summary: Получить все группы
      description: Получить все группы
      parameters:
        - name: sort
          in: query
          schema:
            type: array
            items:
              type: string
              enum:
                - name
                - code
                - createdAt
        - in: query
          name: filter[query]
          description: Фильтрация по имени группы
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'schemas/responses/groups.yaml#/GroupsResponse'
    post:
      tags:
        - group
      summary: Создать новую группу
      description: Создать новую группу
      responses:
        '201':
          description: Создана
          content:
            application/json:
              schema:
                $ref: 'schemas/responses/group.yaml#/GroupResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'schemas/base/group.yaml#/Group'

      
  /groups/{id}:
    get:
      tags:
        - group
      summary: Получить группу по ID
      description: Получить группу по ID
      parameters:
        - name: include
          in: query
          schema:
            type: array
            items:
              type: string
              enum:
                - users
                - projects
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: 'schemas/responses/group.yaml#/GroupResponse'
    put:
      tags:
        - group
      summary: Обновить группу по ID
      description: Обновить группу по ID
      responses:
        '200':
          description: Обновлена
          content:
            application/json:
              schema:
                $ref: 'schemas/responses/group.yaml#/GroupResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'schemas/base/group.yaml#/Group'

    delete:
      tags:
        - group
      summary: Удалить группу по ID
      description: Удалить группу по ID
      responses:
        '204':
          description: Удалена

  /roles:
    get:
      tags:
        - roles
      summary: Получить все роли
      description: Получить все роли
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: 'schemas/responses/roles.yaml#/RolesResponse'

  /groups/{id}/add:
    post:
      tags:
        - group
      summary: Добавить пользователя в группу
      description: Добавить пользователя в группу
      responses:
        '204':
          description: Добавлен
      requestBody:
        content:
          application/json:
            schema:
              properties:
                user_id:
                  type: string
                  format: uuid

  /groups/{id}/remove:
    post:
      tags:
        - group
      summary: Удалить пользователя из группы
      description: Удалить пользователя из группы
      responses:
        '204':
          description: Удален
      requestBody:
        content:
          application/json:
            schema:
              properties:
                user_id:
                  type: string
                  format: uuid