# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/core
    steps:
    - uses: actions/checkout@v4

    - name: Set up
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.0'

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60

    - name: Build
      run: go build -v ./...
  
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/core
    steps:
    - uses: actions/checkout@v4

    - name: Set up
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.0'

    - name: Test
      run: go test -v ./...
